package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"errors"
	"fmt"
	connMongoDB "graphQL/database"
	"graphQL/graph/model"
)

// CreateTrain is the resolver for the createTrain field.
func (r *mutationResolver) CreateTrain(ctx context.Context, input model.NewTrain) (*model.Train, error) {
	train := db.CreateTrain(&input)
	return train, nil
}

// UpdateTrain is the resolver for the updateTrain field.
func (r *mutationResolver) UpdateTrain(ctx context.Context, trainNo int, input model.NewTrain) (*model.Train, error) {
	train := db.UpdateTrain(trainNo, &input)
	if train == nil {
		return nil, fmt.Errorf("No Update Can be Done")
	}
	return train, nil
}

// DeleteTrain is the resolver for the deleteTrain field.
func (r *mutationResolver) DeleteTrain(ctx context.Context, trainNo int) (*model.DeleteTrainInfo, error) {
	deletedTrainCount := db.DeleteTrain(trainNo)
	if deletedTrainCount == nil {
		return nil, errors.New("No train to delete")
	}
	return deletedTrainCount, nil
}

// Gettrains is the resolver for the gettrains field.
func (r *queryResolver) Gettrains(ctx context.Context) ([]*model.Train, error) {
	trains := db.Trains()
	return trains, nil
}

// Gettrain is the resolver for the gettrain field.
func (r *queryResolver) Gettrain(ctx context.Context, trainNo int) (*model.Train, error) {
	train := db.Train(trainNo)
	return train, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = connMongoDB.ConnectToMongoDB()
